// Builds the cspell dictionary of words that appear in the app's UI.
//
// The tests assert on localized strings, so every word in lib/l10n/*.arb is
// legitimately spellable in Dart sources. Collecting them here keeps those
// strings out of per-file `cspell:ignore` comments, which went stale.
//
// Run after changing a translation:
//   dart run tool/gen_cspell_dict.dart

import 'dart:convert';
import 'dart:io';

const _arbDir = 'lib/l10n';
const _output = '.cspell/l10n-words.txt';

void main() {
  final words = <String>{};

  final arbs =
      Directory(_arbDir)
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.arb'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

  for (final arb in arbs) {
    final json = jsonDecode(arb.readAsStringSync()) as Map<String, dynamic>;
    json.forEach((key, value) {
      if (key.startsWith('@') || value is! String) return;
      // {placeholders} are identifiers, not prose
      final prose = value.replaceAll(RegExp(r'\{[^}]*\}'), ' ');
      // lower case: a lower case entry also matches the capitalized and
      // upper case forms, so storing both would just duplicate every
      // German noun
      words.addAll(
        RegExp(
          r'[A-Za-zÀ-ÿ]{2,}',
        ).allMatches(prose).map((m) => m[0]!.toLowerCase()),
      );
    });
  }

  // all lower case, so this is a total order and the output depends only on
  // which words are present -- List.sort is not stable and the set's
  // iteration order shifts whenever a word is added
  final sorted = words.toList()..sort();

  File(_output)
    ..createSync(recursive: true)
    ..writeAsStringSync(
      '# Generated by tool/gen_cspell_dict.dart -- do not edit.\n'
      '# Words used in the app UI (${arbs.map((f) => f.uri.pathSegments.last).join(', ')}),\n'
      '# so that tests may assert on localized strings.\n'
      '${sorted.join('\n')}\n',
    );

  // this is a command line tool, stdout is the interface
  // ignore: avoid_print
  print('$_output: ${sorted.length} words from ${arbs.length} files');
}
