name: Jasstafel Linux CI
on: [push]

# cspell:disable
jobs:
  test-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check out submodule
        run: git submodule update --init --force
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Get dependencies
        run: flutter/bin/flutter pub get
      - name: Generate icons
        run: flutter/bin/flutter pub run flutter_launcher_icons
      - name: Generate translations
        run: flutter/bin/flutter gen-l10n
      - name: Generate sources
        run: flutter/bin/flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Test
        run: flutter/bin/flutter test
      - name: Integration test
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: |
            flutter/bin/flutter config --enable-linux-desktop
            flutter/bin/flutter test integration_test -d linux
